name: Deploy Vite + React to GitHub Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload built files (include binary like mp4)
        uses: actions/upload-artifact@v4
        with:
          name: built-dist
          path: dist
          compression-level: 0     
          if-no-files-found: error 

      - name: Prepare Pages artifact
        run: |
          mkdir upload
          mv dist upload/
        shell: bash

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: upload/dist

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
